!!python/object:train_d_fine.D_FINE.src.core.yaml_config.YAMLConfig
_collate_fn: null
_criterion: null
_ema: null
_evaluator: null
_lr_scheduler: null
_lr_warmup_scheduler: null
_model: null
_optimizer: null
_postprocessor: null
_scaler: null
_train_batch_size: null
_train_dataloader: null
_train_dataset: null
_train_shuffle: null
_val_batch_size: null
_val_dataloader: null
_val_dataset: null
_val_shuffle: null
_writer: null
batch_size: null
checkpoint_freq: 12
clip_max_norm: 0.1
device: ''
ema_decay: 0.9999
ema_warmups: 2000
epoches: 132
find_unused_parameters: false
last_epoch: -1
num_workers: 0
output_dir: Path/to/output/dir # Path to save the output
print_freq: 100
resume: null
seed: null
summary_dir: null
sync_bn: true
task: detection
tuning: Path/to/tuning/weights # Path to model weights for tuning
use_amp: true
use_ema: true
yaml_cfg:
  DFINE:
    backbone: HGNetv2
    decoder: DFINETransformer
    encoder: HybridEncoder
  DFINECriterion:
    alpha: 0.75
    gamma: 2.0
    losses:
    - vfl
    - boxes
    - local
    matcher:
      alpha: 0.25
      gamma: 2.0
      type: HungarianMatcher
      weight_dict:
        cost_bbox: 5
        cost_class: 2
        cost_giou: 2
    reg_max: 32
    weight_dict:
      loss_bbox: 5
      loss_ddf: 1.5
      loss_fgl: 0.15
      loss_giou: 2
      loss_vfl: 1
  DFINEPostProcessor:
    num_top_queries: 300
  DFINETransformer:
    box_noise_scale: 1.0
    cross_attn_method: default
    eval_idx: -1
    feat_channels:
    - 256
    - 256
    - 256
    feat_strides:
    - 8
    - 16
    - 32
    hidden_dim: 256
    label_noise_ratio: 0.5
    layer_scale: 1
    num_denoising: 100
    num_layers: 4
    num_levels: 3
    num_points:
    - 3
    - 6
    - 3
    num_queries: 300
    query_select_method: default
    reg_max: 32
    reg_scale: 4
  HGNetv2:
    freeze_at: -1
    freeze_norm: false
    local_model_dir: weight/hgnetv2/
    name: B2
    pretrained: true
    return_idx:
    - 1
    - 2
    - 3
    use_lab: true
  HybridEncoder:
    act: silu
    depth_mult: 0.67
    dim_feedforward: 1024
    dropout: 0.0
    enc_act: gelu
    expansion: 1.0
    feat_strides:
    - 8
    - 16
    - 32
    hidden_dim: 256
    in_channels:
    - 384
    - 768
    - 1536
    nhead: 8
    num_encoder_layers: 1
    use_encoder_idx:
    - 2
  __include__: # Path to other config files to edit
  - ../dataset/custom_detection.yml
  - ../runtime.yml
  - ../include/dataloader.yml
  - ../include/optimizer.yml
  - ../include/dfine_hgnetv2.yml
  checkpoint_freq: 12
  clip_max_norm: 0.1
  criterion: DFINECriterion
  ema:
    decay: 0.9999
    start: 0
    type: ModelEMA
    warmups: 1000
  epoches: 132
  eval_spatial_size:
  - 640
  - 640
  evaluator:
    iou_types:
    - bbox
    type: CocoEvaluator
  find_unused_parameters: false
  lr_scheduler:
    gamma: 0.1
    milestones:
    - 500
    type: MultiStepLR
  lr_warmup_scheduler:
    type: LinearWarmup
    warmup_duration: 500
  model: DFINE
  num_classes: 13
  optimizer:
    betas:
    - 0.9
    - 0.999
    lr: 0.00025
    params:
    - lr: 2.5e-05
      params: ^(?=.*backbone)(?!.*norm|bn).*$
    - lr: 2.5e-05
      params: ^(?=.*backbone)(?=.*norm|bn).*$
      weight_decay: 0.0
    - params: ^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$
      weight_decay: 0.0
    type: AdamW
    weight_decay: 0.000125
  output_dir: Path/to/output/dir # Path to save the output
  postprocessor: DFINEPostProcessor
  print_freq: 100
  remap_mscoco_category: false
  scaler:
    enabled: true
    type: GradScaler
  sync_bn: true
  task: detection
  train_dataloader:
    collate_fn:
      base_size: 640
      base_size_repeat: 6
      ema_restart_decay: 0.9999
      stop_epoch: 120
      type: BatchImageCollateFunction
    dataset:
      ann_file: Path/to/_annotations.coco.json # Path to annotations file
      img_folder: Path/to/train # Path to training images
      return_masks: false
      transforms:
        ops:
        - p: 0.5
          type: RandomPhotometricDistort
        - fill: 0
          type: RandomZoomOut
        - p: 0.8
          type: RandomIoUCrop
        - min_size: 1
          type: SanitizeBoundingBoxes
        - type: RandomHorizontalFlip
        - size:
          - 640
          - 640
          type: Resize
        - min_size: 1
          type: SanitizeBoundingBoxes
        - dtype: float32
          scale: true
          type: ConvertPILImage
        - fmt: cxcywh
          normalize: true
          type: ConvertBoxes
        policy:
          epoch: 120
          name: stop_epoch
          ops:
          - RandomPhotometricDistort
          - RandomZoomOut
          - RandomIoUCrop
        type: Compose
      type: CocoDetection
    drop_last: true
    num_workers: 0
    shuffle: true
    total_batch_size: 6
    type: DataLoader
  tuning: Path/to/tuning/weights # Path to model weights for tuning
  use_amp: true
  use_ema: true
  use_focal_loss: true
  val_dataloader:
    collate_fn:
      type: BatchImageCollateFunction
    dataset:
      ann_file: Path/to/_annotations.coco.json # Path to annotations file valid
      img_folder:   Path/to/valid # Path to validation images
      return_masks: false
      transforms:
        ops:
        - size:
          - 640
          - 640
          type: Resize
        - dtype: float32
          scale: true
          type: ConvertPILImage
        type: Compose
      type: CocoDetection
    drop_last: false
    num_workers: 0
    shuffle: false
    total_batch_size: 6
    type: DataLoader
